### ISSUE TITLE
Error when converting model

### ISSUE THREAD

**Issue by georgeaidinis** [alexrozanski/LlamaChat#39]
I have downloaded the Llama-2 (13B) models and I have them in .pth format. 

Environment check passes, so does setting up & dependency check. When it reaches the conversion step, I see this:

Writing vocab...

Traceback (most recent call last):
  File "/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert-pth-to-ggml.py", line 11, in <module>
    convert.main(['--outtype', 'f16' if args.ftype == 1 else 'f32', '--', args.dir_model])
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 1144, in main
    OutputFile.write_all(outfile, params, model, vocab)
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 953, in write_all
    for i, ((name, lazy_tensor), ndarray) in enumerate(zip(model.items(), ndarrays)):
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 875, in bounded_parallel_map
    result = futures.pop(0).result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 950, in do_item
    return lazy_tensor.load().to_ggml().ndarray
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 489, in load
    ret = self._load()
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 497, in load
    return self.load().astype(data_type)
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 489, in load
    ret = self._load()
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 549, in load
    ndarrays = [load_unquantized(tensor) for tensor in lazy_tensors]
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 549, in <listcomp>
    ndarrays = [load_unquantized(tensor) for tensor in lazy_tensors]
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 297, in load_unquantized
    tensor = lazy_tensor.load()
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 489, in load
    ret = self._load()
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 695, in load
    return UnquantizedTensor(storage.load(storage_offset, elm_count).reshape(size))
  File "/private/var/folders/m0/872knsrj62s8zllz2f18nhpr0000gn/T/E7FD53F2-B53D-4439-9AE7-898FE0607B18/convert.py", line 679, in load
    raise Exception("tensor stored in unsupported format")
Exception: tensor stored in unsupported format

Am I doing something wrong?

**Comment by georgeaidinis** [comment]
Same issue with #36
